0.2.7: build

diff --git a/bin/genman b/bin/genman
--- a/bin/genman
+++ b/bin/genman
@@ -5,55 +5,18 @@
 set -euo pipefail
 shopt -s inherit_errexit
 
-#######################################
-# generate man page
-# Globals:
-#   author        The author.
-#   bottom_left   Button left text of man page.
-#   desc          Command description for NAME section.
-#   file          Input ascii doctor file.
-#   name          Command or function name.
-#   owner         Git repository owner.
-#   repo          Git repository name.
-#   top_center    Top center text of man page.
-#   top_left      Top left text of man page.
-# Arguments:
-#   1             Output directory.
-#######################################
-adoc() {
-  asciidoctor -b manpage \
-    -a doctitle="${top_left}" \
-    -a author="${author}" \
-    -a manmanual="${top_center}" \
-    -a mansource="${bottom_left}" \
-    -a name="${name}" \
-    -a desc="${desc}" \
-    -a owner="${owner}" \
-    -a repo="${repo}" \
-    -o "${1}" "${file}"
-  tests "${1}"
-}
-
-#######################################
-# git for generated file if file has changed
-# Globals:
-#   src_file      Command source code.
-#######################################
-changed() {
-  git add "${1}" && git commit --quiet -m "${script}" "${1}" >/dev/null 2>&1 && git push --quiet
-  true
-}
+# TODO: meter la url, los common arguments, etc en fichero en share !
+#   si pero los templates tienen que estar en el otro. ... da igual. no da igual.!!!!!
 
 #######################################
 # extract description for header in file
 # Globals:
 #   src_file      Command source code.
 #######################################
-desc-file(){
+manpurpose-file(){
   awk '/^#/ && ! /^#!/ && ! /^##/ && ! /^#$/ && ! /^# shellcheck/ {sub(/^# /, ""); print $0=$0 }' \
     "${src_file}" | head -1 | sed 's/\.$//'
 }
-
 
 #######################################
 # extract description for function in file
@@ -62,7 +25,7 @@ desc-file(){
 # Arguments:
 #   1             Function name.
 #######################################
-desc-func() {
+manpurpose-func() {
   local line_comment="#######################################"
   if grep -qE "^${1}\(\) {" "${src_file}"; then
     tail -r "${src_file}"| awk "/^${1}\() {/{f=1; c=0} f; /${line_comment}/ && ++c==2{f=0}" | \
@@ -71,39 +34,11 @@ desc-func() {
 }
 
 #######################################
-# description
-# Globals:
-#   dest_dir      Destination directory.
-#   dest_file     Destination file path.
-#   dest_filename Destination filename.
-#   tmp_file      Temp file.
-#   tmp_run       Another temp file.
-# Arguments:
-#  None
-#######################################
-run() {
-  local tmp_file tmp_run
-  tmp_run="$(mktemp -d)"
-  [ -d "${dest_dir}" ] || { mkdir -p "${dest_dir}"; touch "${dest_dir}/.gitkeep"; changed "${dest_dir}/.gitkeep"; }
-
-  if [ -f "${dest_file}" ]; then
-    tmp_file="${tmp_run}/${dest_filename}"
-    adoc "${tmp_file}" && if ! cmp -s "${dest_file}" "${tmp_file}"; then
-      mv "${tmp_file}" "${dest_file}"
-      changed "${dest_file}"
-    fi
-  else
-    adoc "${dest_file}" && changed "${dest_file}"
-  fi
-  unset tmp_run
-}
-
-#######################################
 # test generated man page
 # Globals:
 #   author        The author.
 #   bottom_left   Button left text of man page.
-#   name          Command or function name.
+#   manname       Command or function name.
 #   top_center    Top center text of man page.
 #   top_left      Top left text of man page.
 #   top_right     Top right text of man page.
@@ -111,9 +46,40 @@ run() {
 #   1             Generated man page.
 #######################################
 tests() {
-    man -P cat "${1}" | grep -qE \
-    "^${top_left}| ${top_center} |${top_right}$|^${bottom_left}|${name}| ${author} " \
-    || { echo Test Failed: man -P cat "${1}"; exit 1; }
+  if [ "${2-}" ]; then
+    readarray -t page < <(MANPATH="${tmp}${MANPATH:+:${MANPATH}}" COLUMNS=160 man -P cat "$2" "$1")
+  else
+    readarray -t page < <(COLUMNS=160 man -P cat "$1")
+  fi
+
+  for i in "${top_left}" "${top_center}" "${top_right}"; do
+    tests_line "${i}" 0
+  done
+
+  if ! grep -q "${page[5]/       /}" <<< "       ${name_section}"; then
+    echo echo Failed: "${manname}", search: "'${name_section}'", line: "'${page[5]/       /}'"
+    exit 1
+  fi
+
+  for i in "${bottom_left}" "${bottom_right}"; do
+    tests_line "${i}" $(( ${#page[@]}-1 ))
+  done
+}
+
+#######################################
+# test line of man page
+# Globals:
+#   page      man page
+# Arguments:
+#   1         text
+#   2         line number
+#######################################
+tests_line() {
+  local line="${page[${2}]}"
+  if ! grep -q "$1" <<< "${line}"; then
+    echo Failed: "${manname}", search: "'${1}'", line: "'${line}'"
+    exit 1
+  fi
 }
 
 #######################################
@@ -121,14 +87,14 @@ tests() {
 # Globals:
 #   author        The author.
 #   bottom_left   Button left text of man page.
-#   desc          Command description for NAME section,obtained from main function or header in scripts
+#   manpurpose    Command description for NAME section, obtained from main function or header in scripts
 #                 and from function in libraries.
 #   dest_dir      Destination directory.
 #   dest_file     Destination file path
 #   dest_filename Destination filename.
 #   file          Input ascii doctor file.
-#   name          Command or function name.
-#   owner         Git repository owner.
+#   manname       Command or function name.
+#   orgname       Git repository owner.
 #   repo          Git repository name.
 #   src_file      Command source code.
 #   top_center    Top center text of man page.
@@ -138,7 +104,8 @@ tests() {
 #   1             [--desc|--help|--manrepo|--version] [directory]
 #######################################
 main(){
-  local arg dirs path='.' section src version
+  local arg author corner dest dir dirs doctitle file filename find manmanual manpurpose mansource manvolnum
+  local orgname path='.' repo script src version
 
   for arg do
     shift
@@ -148,59 +115,88 @@ main(){
     esac
   done
 
-  cd "$(git top || { echo "${0##*/}: $(pwd): Not a git repository"; exit 1; } )"
+  cd "$(git top || { echo "${0##*/}: $(pwd): Not a git repository" >&2; exit 1; } )"
 
   author="$(git config user.username || { echo "$0: $(pwd): Invalid git username"; exit 1; })"
-  owner="$(git owner || { echo "$0: $(pwd): Invalid git owner"; exit 1; })"
+  orgname="$(git owner || { echo "$0: $(pwd): Invalid git owner"; exit 1; })"
   repo="$(git name || { echo "$0: $(pwd): Invalid git repo name"; exit 1; })"
   script="${0##*/}"
-  version=$(semver next || { echo "$0: $(pwd): Invalid next semver"; exit 1; })
+  version=$(semver next || { echo "$0: $(pwd): Invalid next semver" >&2; exit 1; })
 
+  # FIXME: temporal
+  tmp="$(mktemp -d)"
+  tmp="./tmp"; rm -rf "${tmp}"; mkdir "${tmp}"
+
+  find=( . ); [ ! -d ./src/man ] || find+=( ./src/man )
   while read -r file; do
+    manvolnum=1
     src="${file%.*}"
-    name="${src##*/}"  # name.1 or name
-    case "${name}" in
+    manname="${src##*/}"  # name.1 or name
+    case "${manname}" in
       README)
-        name="$(head -1 README.adoc | awk -F '[()= ]' '/\([1-8])/ { print $3 }')"
-        [ "${name}" != 'doctitle' ] || { echo Invalid Doctitle for README.adoc: "${name}"; exit 1; }
-        section="$(head -1 README.adoc | awk -F '[()= ]' '/\([1-8])/ { print $4 }')"
+        manname="$(head -1 README.adoc | awk -F '[()= ]' '/\([1-8])/ { print $3 }')"
+        [ "${manname}" != 'doctitle' ] || { echo Invalid Doctitle for README.adoc: "${manname}"; exit 1; }
+        manvolnum="$(head -1 README.adoc | awk -F '[()= ]' '/\([1-8])/ { print $4 }')"
         ;;
-      *.[1-8]) section="${name##*.}"; name="${name%.*}"; ;;  # Do not change order !!!
+      *.[1-8]) manvolnum="${manname##*.}"; manname="${manname%.*}"; ;;  # Do not change order !!!
     esac
 
-    dirs=()
-    for d in bin lib sbin; do
-      [ ! -d "${d}" ] || dirs+=("${d}")
-    done
+    dirs=(); for d in bin lib sbin; do [ ! -d "${d}" ] || dirs+=("${d}"); done
 
-    src_file="$(find "${dirs[@]}" -type f -name "${name}")"
+    src_file="$(find "${dirs[@]}" -type f -name "${manname}")"
 
-    # TODO: container and images in this repo and from makefile, build/publish
     if [ "${src_file}" ]; then
-      desc="$(desc-func 'main')"
-      [ "${desc-}" ] || desc="$(desc-file)"
+      manpurpose="$(manpurpose-func 'main')"
+      [ "${manpurpose-}" ] || manpurpose="$(manpurpose-file)"
     else
       while read -r src_file; do
-        desc="$(desc-func "${name}")"
-        [ "${desc-}" ] || break
+        manpurpose="$(manpurpose-func "${manname}")"
+        [ "${manpurpose-}" ] || break
       done < <(find "${dirs[@]}" -type f -name "*.sh")
     fi
-    [ "${desc-}" ] || { echo Invalid Desc for: "${name}"; exit 1; }
+    [ "${manpurpose-}" ] || { echo Invalid Desc for: "${manname}"; exit 1; }
 
-    section="${section:-1}"
+    dest='./share/man'; mkdir -p "${dest}"
+    filename="${manname}.${manvolnum}"  # name.1
+    dir="${tmp}/man${manvolnum}"; mkdir -p "${dir}"
+    output="${dir}/${filename}"
 
-    dest_filename="${name}.${section}"  # name.1
 
-    dest_dir="./share/man/man${section}"
-    dest_file="${dest_dir}/${dest_filename}"
+    manmanual="${manname^} Manual"
+    mansource="${manname^} ${version}"
 
-    bottom_left="${name^} ${version}"
-    top_center="${name^} Manual"
-    top_left="${name^^}(${section})"
-    top_right=${top_left}
-    run
-  done < <(find . ./src/man -type f \( -name "*.adoc" -o -name "README.adoc" \) -mindepth 1 -maxdepth 1)
+    doctitle="${manname^^}(${manvolnum})"
+    asciidoctor -b manpage \
+      -a doctype=manpage \
+      -a doctitle="${doctitle}" \
+      -a manname="${manname}" \
+      -a manpurpose="${manpurpose}" \
+      -a manmanual="${manmanual}" \
+      -a mansource="${mansource}" \
+      -a author="${author}" \
+      -a orgname="${orgname}" \
+      -a repo="${repo}" \
+      -o "${output}" "${file}"
 
+    corner="${manname^^}(${manvolnum})"
+    top_left="^${doctitle} "
+    top_center=" ${manmanual} "
+    top_right=" ${doctitle}$"
+    bottom_left="${mansource} "
+    bottom_right=" ${doctitle}$"
+    name_section="${manname} - ${manpurpose}"
+
+    tests "${output}"
+    tests "${manname}" "${manvolnum}"
+  done < <(find "${find[@]}" -type f \( -name "*.adoc" -o -name "README.adoc" \) -mindepth 1 -maxdepth 1 | grep -v '=')
+
+  if [ -d "${dest}" ]; then
+    if ! git diff --no-index --no-patch "${dest}" "${tmp}"; then
+      rm -rf "${dest:?}"/*
+      cp -r "${tmp}"/* "${dest}"
+      git add "${dest}" && git commit --quiet -m "${script}" "${dest}" >/dev/null 2>&1
+    fi
+  fi
 }
 
 main "$@"
